version: '2'
services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/jedsign-api

  mongo:
    image: mongo
    ports:
      - 27017:27017
